Repository spectrochempy/spectrochempy, pull requests merged in 2020-06, with the labels that each got.

#89 Feature/tutorials
  docs/user/tutorials/IO/Import.py
  docs/user/tutorials/IO/ImportIR.py
  docs/user/tutorials/analysis/figures/prominence.png
  docs/user/tutorials/analysis/figures/prominence_algo.png
  docs/user/tutorials/analysis/figures/prominence_wlen.png
  docs/user/tutorials/analysis/figures/width_algo.jpg
  docs/user/tutorials/analysis/mcr_als.py
  docs/user/tutorials/analysis/peak_finding.py
  docs/user/tutorials/analysis/peak_integration.py
  docs/user/tutorials/processing/baseline_correct.py
  docs/user/tutorials/processing/slicing.py
  docs/user/tutorials/processing/smoothing.py
  spectrochempy/core/analysis/peakfinding.py
  spectrochempy/core/processors/filter.py
  spectrochempy/core/processors/smooth.py
  tests/test_analysis/test_find_peaks.py
  tests/test_processors/test_smooth.py
Labels: documentation

#99 DEV read_omnic()
  spectrochempy/core/readers/readomnic.py
  spectrochempy/units/units.py
Labels: enhancement

#101 Feature/travis deploy - taking into account restrictions regarding secure keys
  .ci/conda-upload.sh
  .lgtm.yml
  .travis.yml
  README.md
  conda/meta.yaml
  docs/conf.py
  docs/user/tutorials/IO/Import.py
  docs/user/tutorials/IO/ImportIR.py
  env/scpy-dev.yml
  env/scpy.yml
  requirements.txt
  spectrochempy/api.py
  spectrochempy/core/dataset/ndarray.py
  spectrochempy/core/dataset/ndcoord.py
  spectrochempy/core/dataset/ndcoordrange.py
  spectrochempy/core/dataset/ndio.py
  spectrochempy/core/processors/concatenate.py
  spectrochempy/extern/sphinxext/__init__.py
  spectrochempy/extern/sphinxext/autodocsumm/LICENSE_AUTODOCSUMM
  spectrochempy/extern/sphinxext/autodocsumm/__init__.py
  spectrochempy/extern/sphinxext/traitlets_sphinxdoc/LICENSE_TRAITLETS
  spectrochempy/extern/sphinxext/traitlets_sphinxdoc/__init__.py
Labels: enhancement

#105 CI: continuing setup
  .ci/scripts/conda-upload.sh
  .ci/scripts/get-version.sh
  .travis.yml
Labels: enhancement

#114 CI: Travis deploy and build doc improved
  .ci/scripts/conda-upload.sh
  .ci/scripts/get-version.sh
  .travis.yml
Labels: enhancement

#116 CI: try to fix bug on deploy
  .ci/scripts/get-version.sh
  docs/make.py
  spectrochempy/utils/system.py
  tests/test_utils/test_system.py
Labels: bug

#120 Feature/travis deploy
  .ci/scripts/conda-upload.sh
  CHANGELOG.md
Labels: bug

#127 FIX: an indentation error
  spectrochempy/core/analysis/iris.py
Labels: bug

#128 FIX: modify the way update are checked.
  .gitignore
  setup.cfg
  spectrochempy/__init__.py
  spectrochempy/api.py
  spectrochempy/application.py
  spectrochempy/core/__init__.py
  spectrochempy/scripts/scpy.py
  spectrochempy/scripts/scpy_update.py
  spectrochempy/utils/qtfiledialogs.py
  spectrochempy/utils/system.py
Labels: bug
