Repository spectrochempy/spectrochempy, pull requests merged in 2025-02, with the labels that each got.

#808 Docs/documentation
  .ci/generate_requirements.py
  .ci/templates/meta.tmpl
  .github/workflows/build_docs.yml
  .github/workflows/scripts/generate_conda_recipe.py
  docs/_static/js/versions.js
  docs/_static/versions.json
  docs/_templates/layout.html
  docs/conf.py
  docs/make.py
  docs/sources/credits/citing.rst
  docs/sources/credits/credits.rst
  docs/sources/gettingstarted/overview.py
  docs/sources/userguide/analysis/fitting.py
  docs/sources/userguide/analysis/mcr_als.py
  docs/sources/userguide/analysis/pca.py
  docs/sources/userguide/analysis/peak_finding.py
  docs/sources/userguide/analysis/peak_integration.py
  docs/sources/userguide/analysis/pls.py
  docs/sources/userguide/api/api.py
  docs/sources/userguide/importexport/import.py
  docs/sources/userguide/importexport/importIR.py
  docs/sources/userguide/introduction/interface.py
  docs/sources/userguide/introduction/introduction.py
  docs/sources/userguide/introduction/mdcheatsheet.py
  docs/sources/userguide/objects/dataset/dataset.py
  docs/sources/userguide/objects/project/project.py
  docs/sources/userguide/plotting/plotting.py
  docs/sources/userguide/processing/alignment.py
  docs/sources/userguide/processing/apodization.py
  docs/sources/userguide/processing/baseline.py
  docs/sources/userguide/processing/denoising.py
  docs/sources/userguide/processing/fourier.py
  docs/sources/userguide/processing/interferogram.py
  docs/sources/userguide/processing/math_operations.py
  docs/sources/userguide/processing/slicing.py
  docs/sources/userguide/processing/smoothing.py
  docs/sources/userguide/processing/td_baseline.py
  docs/sources/userguide/processing/transformations.py
  docs/tools/helpers.py
  docs/tools/regenerate_docs.py
  docs/tools/req_old_scpy.txt
  environments/environment.yml
  environments/environment_cantera.yml
  environments/environment_dev.yml
  environments/environment_docs.yml
  environments/environment_interactive.yml
  environments/environment_test.yml
  pyproject.toml
  recipe/meta.yaml
  requirements/requirements.txt
  requirements/requirements_docs.txt
  src/spectrochempy/core/dataset/nddataset.py
  src/spectrochempy/utils/print_versions.py
Labels: documentation

#810 Docs/documentation
  .github/workflows/build_docs.yml
  .gitignore
  docs/conf.py
  docs/make.py
  docs/sources/devguide/code_style.rst
  docs/sources/devguide/codespec_adding_reader.rst
  docs/sources/devguide/contributing.rst
  docs/sources/devguide/contributing_codebase.rst
  docs/sources/devguide/contributing_docstring.rst
  docs/sources/devguide/contributing_documentation.rst
  docs/sources/devguide/docker.rst
  docs/sources/devguide/docker_build.md
  docs/sources/devguide/issues.rst
  docs/sources/gettingstarted/getting_help.rst
  docs/sources/gettingstarted/install/index.rst
  docs/sources/gettingstarted/install/install_adds.rst
  docs/sources/gettingstarted/install/install_colab.rst
  docs/sources/gettingstarted/install/install_docker.rst
  docs/sources/gettingstarted/install/install_mac.rst
  docs/sources/gettingstarted/install/install_mac_linux.rst
  docs/sources/gettingstarted/install/install_sources.rst
  docs/sources/gettingstarted/install/install_win.rst
  docs/sources/gettingstarted/overview.py
  docs/sources/gettingstarted/whyscpy.rst
  docs/sources/index.rst
  docs/sources/index.rst.tmpl
  docs/sources/userguide/analysis/fitting.py
  docs/sources/userguide/analysis/index.rst
  docs/sources/userguide/analysis/peak_finding.py
  docs/sources/userguide/importexport/import.py
  docs/sources/userguide/importexport/importIR.py
  docs/sources/userguide/index.rst
  docs/sources/userguide/introduction/introduction.py
  docs/sources/userguide/objects/dataset/dataset.py
  docs/sources/whatsnew/index.rst
  environments/environment_docs.yml
  pyproject.toml
  requirements/requirements_docs.txt
  setup.cfg
  src/spectrochempy/application/plot_preferences.py
  src/spectrochempy/core/dataset/nddataset.py
  tests/test_extern/test_nmrglue.py
Labels: documentation

#811 TESTS: updated extern module tests
  docs/sources/whatsnew/changelog.rst
  src/spectrochempy/api.py
  src/spectrochempy/extern/traittypes.py
  src/spectrochempy/extern/traittypes_utils.py
  src/spectrochempy/structure.md
  tests/test_extern/test_nmrglue.py
  tests/test_extern/test_traittypes.py
  tests/test_extern/test_whittaker.py
Labels: code review

#812 FIX: prepare new version workflow
  .github/workflows/prepare_new_release.yml
  .github/workflows/scripts/update_version_and_release_notes.py
  pyproject.toml
Labels: bug

#813 FIX: prepare new release version workflow.
  .ci/condarc.yml
  .github/dependabot.yml
  .github/workflows/build_package.yml
  .github/workflows/prepare_new_release.yml
  .github/workflows/scripts/update_version_and_release_notes.py
  .github/workflows/test_package.yml
  CITATION.cff
  zenodo.json
Labels: bug, code review

#822 fix to issue #696 coordset subtraction
  docs/sources/userguide/objects/dataset/dataset.py
  docs/sources/whatsnew/changelog.rst
  src/spectrochempy/core/dataset/coordset.py
  tests/test_core/test_dataset/test_coordset.py
Labels: bug

#832 FIX: bug #827
  docs/sources/whatsnew/changelog.rst
  docs/sources/whatsnew/v0.7.1.rst
  src/spectrochempy/application/application.py
  tests/test_application/test_application.py
Labels: bug
